# Generated by Django 2.1.11 on 2019-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='address',
            field=models.CharField(default='No data', max_length=200),
        ),
    ]
