# Generated by Django 2.1.11 on 2019-09-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contactform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
