# Generated by Django 2.1.11 on 2019-09-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_auto_20190906_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
