# Generated by Django 2.1.11 on 2019-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_auto_20190906_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
