# Generated by Django 2.1.11 on 2019-09-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_contactform_ip_address_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='ip_address_string',
        ),
    ]
