# Generated by Django 2.1.11 on 2019-09-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
