# Generated by Django 2.1.11 on 2019-09-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_category', models.CharField(max_length=64, null=True)),
                ('img_alt', models.CharField(max_length=64)),
                ('img_notes', models.CharField(max_length=200, null=True)),
                ('img_before', models.ImageField(null=True, upload_to='images/')),
                ('img_after', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Images',
            },
        ),
    ]
