# Generated by Django 2.1.11 on 2019-09-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='img_notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
