# Generated by Django 2.1.11 on 2019-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimages',
            old_name='img_after',
            new_name='After_Picture',
        ),
        migrations.RenameField(
            model_name='uploadedimages',
            old_name='img_before',
            new_name='Before_Picture',
        ),
        migrations.RenameField(
            model_name='uploadedimages',
            old_name='img_category',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='uploadedimages',
            name='img_alt_after',
        ),
        migrations.RemoveField(
            model_name='uploadedimages',
            name='img_alt_before',
        ),
        migrations.RemoveField(
            model_name='uploadedimages',
            name='img_notes',
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='After_Picture_Description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Before_Picture_Description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Notes',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
