# Generated by Django 2.1.11 on 2019-09-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0002_auto_20190907_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='After_Picture_Size_kB',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Before_Picture_Dimension',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Before_Picture_Size_kB',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
