# Generated by Django 2.1.11 on 2019-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0002_uploadedimages_img_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimages',
            options={'verbose_name_plural': 'Uploaded Images'},
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='img_category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='img_alt',
            field=models.CharField(max_length=64),
        ),
    ]
