# Generated by Django 2.1.11 on 2019-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0003_auto_20190906_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='img_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
