# Generated by Django 2.1.11 on 2019-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0004_auto_20190911_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimages',
            old_name='Before_Picture_Dimension',
            new_name='After_Picture_Max_Dimension',
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Before_Picture_Max_Dimension',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='After_Picture_Description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Before_Picture_Description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
