# Generated by Django 2.1.11 on 2019-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0005_auto_20190911_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='After_Picture_Max_Dimension',
            field=models.IntegerField(default=768, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='After_Picture_Size_kB',
            field=models.IntegerField(default=140, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Before_Picture_Max_Dimension',
            field=models.IntegerField(default=768, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Before_Picture_Size_kB',
            field=models.IntegerField(default=140, null=True),
        ),
    ]
