# Generated by Django 2.1.11 on 2019-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0007_auto_20190912_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='Category',
            field=models.CharField(choices=[('None', 'Select a Category'), ('Houses', 'Houses'), ('Decks', 'Decks'), ('Deck Staining', 'Deck Staining'), ('Concrete & Brick', 'Concrete & Brick'), ('Fences', 'Fences'), ('Graffiti Removal', 'Graffiti Removal')], default='None', max_length=64, null=True),
        ),
    ]
